# ============================================
# Docker Compose - Desarrollo Local
# ============================================
# Uso: docker-compose up -d
# ============================================

services:
  # ==========================================
  # MongoDB Database
  # ==========================================
  mongodb:
    image: mongo:7.0-alpine
    container_name: sirha-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:-admin123}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE:-sirha_dev}
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - sirha-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  # ==========================================
  # SIRHA Backend Application
  # ==========================================
  sirha-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sirha-backend
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      # Spring Profile
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-development}
      
      # Server Configuration
      SERVER_PORT: 8081
      
      # MongoDB Connection
      MONGODB_URI: mongodb://${MONGODB_USERNAME:-admin}:${MONGODB_PASSWORD:-admin123}@mongodb:27017
      MONGODB_DATABASE: ${MONGODB_DATABASE:-sirha_dev}
      
      # JWT Configuration (¡CAMBIAR EN PRODUCCIÓN!)
      JWT_SECRET: ${JWT_SECRET:-changeme-dev-secret-key-minimum-32-characters-long-for-security}
      
      # Java Options
      JAVA_OPTS: "-Xms256m -Xmx512m"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - sirha-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s

# ==========================================
# Networks
# ==========================================
networks:
  sirha-network:
    driver: bridge

# ==========================================
# Volumes
# ==========================================
volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
