spring:
  application:
    name: sirha
  # Cargar variables desde archivo .env
  context:
    initializer:
      classes: edu.dosw.sirha.config.DotenvApplicationContextInitializer
  data:
    root: INFO
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,threaddump,loggers
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized

sirha:
  security:
    jwt:
      issuer: sirha
      expiration-minutes: ${JWT_EXPIRATION_MINUTES:60}
      secret: ${JWT_SECRET}  # REQUERIDO - No hay valor por defecto
  solicitudes:
    dias-max-respuesta: ${DIAS_MAX_RESPUESTA:5}
  admin:
    # Configuraci贸n del usuario ADMIN inicial (solo para primera instalaci贸n)
    # Estos valores deben venir de variables de entorno por seguridad


---
spring:
  config:
    activate:
      on-profile: development
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017}
      database: ${MONGODB_DATABASE:SIRHA}

logging:
  level:
    root: DEBUG
    edu.dosw.sirha: DEBUG

---
spring:
  config:
    activate:
      on-profile: production

logging:
  level:
    root: WARN
    edu.dosw.sirha: INFO

# En producci贸n, TODAS las variables deben venir del entorno
# NO usar valores por defecto en producci贸n