spring:
  config:
    activate:
      on-profile: development
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/sirha-dev}
      database: ${MONGODB_DATABASE:sirha_sbx}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    ssl: ${REDIS_SSL:false}

sirha:
  jwt:
    secret: ${JWT_SECRET:changeme-dev}

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
