name: Integraci칩n Continua

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  JAVA_VERSION: '17'

jobs:
  unit-test:
    name: Test y An치lisis de Calidad
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: test

    steps:
      - name: Obtener c칩digo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Temurin JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      - name: Cachear dependencias de Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Verificar proyecto (tests + cobertura)
        run: mvn -B -Dspring.profiles.active=test verify jacoco:report

      - name: Publicar reporte de pruebas Maven
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Maven Unit Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit

      - name: Subir cobertura JaCoCo a Codecov
        uses: codecov/codecov-action@v4
        with:
          file: target/site/jacoco/jacoco.xml
          flags: unittests
          name: sirha-backend-coverage

      - name: Subir artifact del build (JAR)
        uses: actions/upload-artifact@v4
        with:
          name: sirha-backend-jar
          path: target/*.jar

  security-scan:
    name: Escaneo de Dependencias y Contenedores
    needs: unit-test
    runs-on: ubuntu-latest

    steps:
      - name: Obtener c칩digo
        uses: actions/checkout@v4

      - name: Ejecutar Trivy scan (filesystem)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Subir resultados Trivy a code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
